Main svc
IvanSuchilin/java-explore-with-me pull request #3
Opened 2023-02-13 13:53 UTC by IvanSuchilin

2023-02-15 05:56 UTC, Fleaman777 requested changes

2023-02-15 05:56 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/ewm/exceptions/RequestValidationExceptions/NameAlreadyExistException.java
> +public class NameAlreadyExistException extends RuntimeException {
как вариант, этот эксепшены и ниже можно было бы наследовать от какого-нибудь общего, а этот общий содержал бы все необхожимые поля, и сам наследовался бы от RuntimeException

2023-02-15 05:56 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/ewm/publicApi/controller/PublicController.java
> +        log.info("endpoint path: {}", request.getRequestURI());
если нет какого-то особого смысла иметь 2 лога, то можно было бы их объеденить

2023-02-15 05:56 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/ewm/request/service/RequestService.java
> +    }
попробуй этот метод немного разделить сократить, какую-нибудь часть вынести в отдельный приватный метод,

2023-02-15 05:56 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/ewm/request/service/RequestService.java
> +}
этот длинный метод тоже можно было бы немного разделить

2023-02-15 05:56 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/ewm/user/service/UserService.java
> +        log.debug("Получен запрос DELETE /admin/users/{userId}");
этот лог может быть некорректным, например в случае, когда этот метод deleteUser будет вызван другим сервисом

аналалагично в др похожих местах

2023-02-15 05:56 UTC, Fleaman777 commented on explore-main/src/main/java/ru/practicum/ewm/validation/DtoValidator.java
> +                    LocalDateTime.now());
LocalDateTime.now() - можно было бы вынести в локальную переменную

аналагично в методе ниже

2023-02-15 08:39 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/category/service/CategoryService.java
> +        if (updatingDto.getName() != null || !updatingDto.getName().isBlank()) {
Внедрил

2023-02-15 08:58 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/category/service/CategoryService.java
> +                    .anyMatch(u -> u.getName().equals(updatingDto.getName()))) {
сделано

2023-02-15 09:01 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/publicApi/controller/PublicController.java
> +        log.info("endpoint path: {}", request.getRequestURI());
Done

2023-02-15 09:15 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/request/service/RequestService.java
> +    }
Done

2023-02-15 09:26 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/user/service/UserService.java
> +        log.debug("Получен запрос DELETE /admin/users/{userId}");
Done

2023-02-15 09:49 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/request/service/RequestService.java
> +}
Done

2023-02-15 10:00 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/compilation/service/CompilationService.java
> +                .collect(Collectors.toList());
Поправил вроде бы везде, где нашел

2023-02-15 10:27 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/exceptions/RequestValidationExceptions/NameAlreadyExistException.java
> +public class NameAlreadyExistException extends RuntimeException {
Done

2023-02-15 10:41 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/compilation/service/CompilationService.java
> +                .stream().map(EventMapper.INSTANCE::toCompilationDtoFromFull).collect(Collectors.toList());
Перенес маппинг в метод

2023-02-15 14:10 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/category/service/CategoryService.java
> +                    LocalDateTime.now());
Перенес в валидацию проверку

2023-02-15 14:19 UTC, IvanSuchilin commented on explore-main/src/main/java/ru/practicum/ewm/validation/DtoValidator.java
> +                    LocalDateTime.now());
done

2023-02-16 06:29 UTC, Fleaman777 approved these changes

2023-02-16 07:59 UTC, merged